name: build
on:
  push:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: cd tests && npm install
      - run: cd tests && npm run build
