name: build
on:
  push:
    branches: [ '*' ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Deploy Playground
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cd sof-js && bun install &&  bun test && bun build src/index.js  > ../test_report/public/processor.js
      - run: cd test_report && bun install && bun run prepare && bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'test_report/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
